## To get product list
GET http://localhost:6000/api/v1/orders?page=0&size=30
Accept: application/json

###

## To get order detail
GET http://localhost:6000/api/v1/orders/62b8f7c0d7b7e8204b72bb60
Accept: application/json

###

## To insert order
POST http://localhost:6000/api/v1/orders
Content-Type: application/json

{
  "customer": "Rolando Condorena",
  "items": [
    {
      "productId": "62b692c6a311f10e7f3f35da",
      "name": "Chocolate Cake",
      "category": "Cakessss",
      "unitPrice": 60,
      "active": true
    },
    {
      "productId": "62b692c6a3dede0e7f3f35da",
      "name": "Chocolate",
      "category": "Sweet",
      "unitPrice": 40,
      "active": true
    }
  ]
}

###

## To update order
PUT http://localhost:6000/api/v1/orders/62b94500d1ef3517052fcd51
Content-Type: application/json

{
  "status": "Rejected",
  "items": [
    {
      "productId": "62b692c6a311f10e7f3f35da",
      "name": "Chocolate Cake",
      "category": "Cakessss",
      "unitPrice": 20,
      "active": true
    },
    {
      "productId": "62b692c6a3dede0e7f3f35da",
      "name": "Chocolate",
      "category": "Sweet",
      "unitPrice": 40,
      "active": true
    }
  ]
}

###



## To delete order
PUT http://localhost:6000/api/v1/orders/62b8f7c0d7b7e8204b72bb60
Content-Type: application/json

###



