## To get product list
GET http://localhost:6000/api/v1/products
Accept: application/json
###


## To insert product
POST http://localhost:6000/api/v1/products
Content-Type: application/json

{
  "name": "Chocolate Cake",
  "category": "Cakes",
  "unitPrice": 25,
  "active": true
}
###

## To insert product
PUT http://localhost:6000/api/v1/products/62b692c6a311f10e7f3f35da
Content-Type: application/json

{
  "name": "Chocolate Cake",
  "category": "Cakessss",
  "unitPrice": 25,
  "active": true
}
###



