## To get product list
GET {{host}}/orders?page=0&size=30
Accept: application/json

###

## To get order detail
GET {{host}}/orders/62b8f7c0d7b7e8204b72bb60
Accept: application/json

###

## To insert order
POST {{host}}/orders
Content-Type: application/json

{
  "customer": "Rolando Condorena",
  "items": [
    {
      "productId": "62b692c6a311f10e7f3f35da",
      "name": "Chocolate Cake",
      "category": "Cakessss",
      "unitPrice": 10,
      "quantity": 6,
      "active": true
    },
    {
      "productId": "62b692c6a3dede0e7f3f35da",
      "name": "Chocolate",
      "category": "Sweet",
      "unitPrice": 5,
      "quantity": 8,
      "active": true
    }
  ]
}

###

## To update order
PUT {{host}}/orders/62ba5f13a6f7b3457e04c7bc
Content-Type: application/json

{
  "status": "Rejected",
  "items": [
    {
      "productId": "62b692c6a311f10e7f3f35da",
      "name": "Chocolate Cake",
      "category": "Cakessss",
      "unitPrice": 10,
      "quantity": 5,
      "active": true
    },
    {
      "productId": "62b692c6a3dede0e7f3f35da",
      "name": "Chocolate",
      "category": "Sweet",
      "unitPrice": 5,
      "quantity": 8,
      "active": true
    }
  ]
}

###



## To delete order
DELETE {{host}}/orders/62ba2376082e8b7c92a89a26
Content-Type: application/json

###



