## To get product list
GET {{host}}/products?page=0&size=100
Accept: application/json
###


## To insert product
POST {{host}}/products
Content-Type: application/json

{
  "name": "PPP",
  "category": "Cakes",
  "unitPrice": 25,
  "active": true
}
###

## To update product
PUT {{host}}/products/62ba1f03082e8b7c92a89a25
Content-Type: application/json

{
  "name": "TTT",
  "category": "Cakessss",
  "unitPrice": 2000,
  "active": true
}
###

## To delete product
DELETE {{host}}/products/62b88dcc10bcac62b677a353
Content-Type: application/json

###


